# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foxglove/MagneticField.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'foxglove/MagneticField.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from foxglove import Vector3_pb2 as foxglove_dot_Vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66oxglove/MagneticField.proto\x12\x08\x66oxglove\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16\x66oxglove/Vector3.proto\"\x9e\x01\n\rMagneticField\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12)\n\x0emagnetic_field\x18\x03 \x01(\x0b\x32\x11.foxglove.Vector3\x12!\n\x19magnetic_field_covariance\x18\x04 \x03(\x01\x42\x16\n\x14\x64\x65v.foxglove.schemasb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foxglove.MagneticField_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024dev.foxglove.schemas'
  _globals['_MAGNETICFIELD']._serialized_start=100
  _globals['_MAGNETICFIELD']._serialized_end=258
# @@protoc_insertion_point(module_scope)
